name: CI

on: [push, pull_request]

jobs:
  gitlab:
    name: Build and deploy
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ESS pipeline
        uses: appleboy/gitlab-ci-action@master
        with:
          token: ${{ secrets.TOKEN }}
          project_id: 5167
          ref: "main"
          host: https://gitlab.esss.lu.se
          debug: true
