name: CI

on: [push, pull_request]

jobs:
  test-dev-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          cp CI/dev/dev-routing.config.json config/routing.config.json
          
    